### ISSUE TITLE
Transition gets applied only once

### ISSUE THREAD

**Issue by minedun6** [euvl/vue-js-modal#197]
The first time after a page loading, when i show the modal, the transition is called perfectly on showing, but after closing it and re-showing it, it just pops-up with no transition.

**Comment by euvl** [comment]
This is very strange, can you share your code pls?

**Comment by euvl** [comment]
Closed as inactive

**Comment by minedun6** [comment]
Sorry didn't get time to check this out, refreshing this issue out.

will be sure to provide some code snippet later in the evening

**Comment by nintra** [comment]
I got the same problem. I created a modal with:
``` vue
<modal name="overlay" height="auto" @before-open="beforeShow"  @opened="opened" @before-close="beforeHide" @closed="closed" :scrollable="true" transition="overfade">
    <div class="inner"></div>
</modal>
```
``` scss
.v--modal-overlay{
    .v--modal-box{
        &.overfade-enter,
        &.overfade-leave-to {
            opacity: 0;
            transform:translate(0, 1rem);
        }

        &.overfade-enter-to,
        &.overfade-leave {
            opacity: 1;
            transform:translate(0, 0);
        }

        &.overfade-enter-active {
            transition:opacity $overlay-transition-duration $ease-out-cubic, transform $overlay-transition-duration $ease-out-cubic;
        }

        &.overfade-leave-active {
            transition:opacity $overlay-transition-duration $ease-in-cubic, transform $overlay-transition-duration $ease-in-cubic;
        }
    }
}
```
``` js
self.$modal.show('overlay');
```

But my transition class is only applied on `enter` not on `leave`. On `leave` it just shows the default transition `overlay-fade`.
