### ISSUE TITLE
Opening modal with scrollable: true cause viewport to jump to top

### ISSUE THREAD

**Issue by amoshydra** [euvl/vue-js-modal#205]
This happen after the inclusion of #188.

### What work:
Removing overflow hidden from either `body` or `html`

Example:
1. remove `overflow: hidden` from body
    ```scss
    body.v--modal-block-scroll {
      overflow: initial;
    }
    ```
2. remove `overflow: hidden` from html (i.e. removing #188)
    ```scss
    html.v--modal-block-scroll {
      overflow: initial;
    }
    ```

### What doesn't resolve this problem
1. Removing `position` attribute from `body`
1. Removing `position` attribute from `html`
1. Removing `position` attribute from `body` and `html`
1. Removing `overflow` attribute from `body` and `html`

**Comment by euvl** [comment]
so what is your suggestion?

**Comment by amoshydra** [comment]
@euvl
Sorry, I have found that this is not a `vue-js-modal`'s problem.  
Setting `overflow: hidden;` on both html and body alone does not cause this issue. https://codepen.io/amoshydra/pen/eMWELr


The reason why my project suffer from this problem was because we had this styling applied.
```scss
html,
body {
  height: 100%;
}
```
