### ISSUE TITLE
Style for modal doesn't work in media queries

### ISSUE THREAD

**Issue by kentforth** [euvl/vue-js-modal#615]
When I try to apply style for modal in media queries it doesn't work

I tried to change width of modal to 300px when screen resolution is 768px

**How can I fix it?**

```
<modal name="my-first-modal" height="auto" :reset="true" :width="700">
</modal>
```

CSS:

```
@media screen and (max-width: 768px) {
  .vm--modal {
    width: 300px;
  }
}
```

**Comment by embluk** [comment]
I was having the same issue, doesn't seem to be native support for this use case, so I had to change and override the CSS to get it working with different heights and widths when the screen size changes.

For example, this worked for me:

```css
@media screen and (min-width: 2500px)
{
    .modal
    {
        height: 68% !important;
        width: 60% !important;
        top: 0 !important;
        left: 0 !important;
    }

    .vm--container
    {
        display: flex;
        justify-content: center;
        align-items: center;
    }
}
```

Where `.modal` is assigned by using the `classes` prop with this plugin. I then set my initial height and width using the `height` and `width` props also.

Hope this helps.
